// src/networking/grpc/mod.rs

// This will include the Rust code generated by tonic_build from your .proto files.
// The actual module names will match your package names in the .proto files.
// For example, if you have `package greeter;` in a .proto file,
// you'll have `pub mod greeter;` here.

pub mod generated {
    // Include the generated files. The `include!` macro is often used here,
    // or you can directly include the generated `*.rs` files if you know their names.
    // tonic::include_proto! will look for a file named based on your package name
    // (e.g., "greeter.rs") in the OUT_DIR specified in build.rs.
    
    // For the dummy "greeter.proto"
    pub mod greeter {
        tonic::include_proto!("greeter"); // Corresponds to greeter.proto
    }
    // For the dummy "common.proto"
    pub mod common {
        tonic::include_proto!("common"); // Corresponds to common.proto
    }
    // Add more here as you define more packages in your .proto files
}

// You might also define your server implementations and client logic in submodules here.
// For example:
// pub mod server;
// pub mod client;
